# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

#define MIRYOKU_KLUDGE_MOUSEKEYSPR
#define U_MOUSE_MOVE_MAX 2500
#define U_MOUSE_SCROLL_MAX 30
#undef MOVE_UP
#undef MOVE_DOWN
#undef MOVE_LEFT
#undef MOVE_RIGHT
#undef SCROLL_UP
#undef SCROLL_DOWN
#undef SCROLL_LEFT
#undef SCROLL_RIGHT
#define MOVE_UP MOVE_VERT(-U_MOUSE_MOVE_MAX)
#define MOVE_DOWN MOVE_VERT(U_MOUSE_MOVE_MAX)
#define MOVE_LEFT MOVE_HOR(-U_MOUSE_MOVE_MAX)
#define MOVE_RIGHT MOVE_HOR(U_MOUSE_MOVE_MAX)
#define SCROLL_UP SCROLL_VERT(U_MOUSE_SCROLL_MAX)
#define SCROLL_DOWN SCROLL_VERT(-U_MOUSE_SCROLL_MAX)
#define SCROLL_LEFT SCROLL_HOR(-U_MOUSE_SCROLL_MAX)
#define SCROLL_RIGHT SCROLL_HOR(U_MOUSE_SCROLL_MAX)


name: "My Build Example mousekeyspr"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left", "corne_right"]'
      alphas: '["qwerty"]'
      extra: '["colemakdh"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define U_MOUSE_MOVE_MAX 2500\n#define U_MOUSE_SCROLL_MAX 30\n#undef MOVE_UP\n#undef MOVE_DOWN\n#undef MOVE_LEFT\n#undef MOVE_RIGHT\n#undef SCROLL_UP\n#undef SCROLL_DOWN\n#undef SCROLL_LEFT\n#undef SCROLL_RIGHT\n#define MOVE_UP MOVE_VERT(-U_MOUSE_MOVE_MAX)\n#define MOVE_DOWN MOVE_VERT(U_MOUSE_MOVE_MAX)\n#define MOVE_LEFT MOVE_HOR(-U_MOUSE_MOVE_MAX)\n#define MOVE_RIGHT MOVE_HOR(U_MOUSE_MOVE_MAX)\n#define SCROLL_UP SCROLL_VERT(U_MOUSE_SCROLL_MAX)\n#define SCROLL_DOWN SCROLL_VERT(-U_MOUSE_SCROLL_MAX)\n#define SCROLL_LEFT SCROLL_HOR(-U_MOUSE_SCROLL_MAX)\n#define SCROLL_RIGHT SCROLL_HOR(U_MOUSE_SCROLL_MAX)"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y\nCONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y\nCONFIG_ZMK_BLE_PASSKEY_ENTRY=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
